# -*- coding: utf-8 -*-
"""Extract the free factual columns from the paid projection workbooks.

Those workbooks are not built into the board -- they are a paid product. What
this pulls out is not projection work:

  * POS  -> per-platform position eligibility. The same projections are
           published twice, once against each platform's rules, and the two
           differ on the POS column for 133 players. The rulings are Yahoo's
           and Fantrax's own, published free on both sites.
  * AGE  -> a player's age, used for the board's pre/post-prime marker.

Re-run whenever the workbooks are republished; the CSVs are a snapshot, not a
live read. Both are plain CSV and safe to hand-edit.

    python make_reference.py
"""

from __future__ import print_function, unicode_literals

import io
import os
import sys

from drafttool import config as cfg_mod
from drafttool import eligibility
from drafttool import sources as sources_mod

# workbook -> the provider id it publishes eligibility for.
WORKBOOKS = [
    ("yahoo", "2026-27-Fantasy-Projections-Yahoo-1.xlsx"),
    ("fantrax", "2026-27-Fantasy-Projections-Fantrax-1.xlsx"),
]

SHEET = "The List"
HEADER_ROW = 1
FIRST_DATA_ROW = 2
NAME_COL = 2
POS_COL = 4
AGE_COL = 7


def _rows(filename):
    # Reuse the reader the build uses -- load_rows resolves the name against
    # sources/ itself -- so shared strings, sparse cells and encoding are
    # handled exactly one way in this project.
    return sources_mod.load_rows({"id": "REF", "file": filename}, SHEET, 200)


def read_positions(filename):
    """Return [(display name, [positions])] from a workbook's player list."""
    out = []
    for raw in _rows(filename)[FIRST_DATA_ROW - 1:]:
        name = sources_mod._cell(raw, NAME_COL - 1)
        pos = sources_mod._cell(raw, POS_COL - 1)
        if not name or not pos:
            continue
        positions = eligibility._positions(str(pos))
        if positions:
            out.append((str(name).strip(), positions))
    return out


def read_ages(filename):
    """Return [(display name, age)] from a workbook's player list."""
    out = []
    for raw in _rows(filename)[FIRST_DATA_ROW - 1:]:
        name = sources_mod._cell(raw, NAME_COL - 1)
        age = sources_mod._number(sources_mod._cell(raw, AGE_COL - 1))
        if not name or age is None:
            continue
        out.append((str(name).strip(), int(round(age))))
    return out


def _write(path, banner, header, rows, render):
    with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("# %s, generated by make_reference.py\n"
                     "# Re-run that script when the workbooks are republished."
                     "\n# Hand edits are fine: this is plain CSV, one player per"
                     "\n# line, and '#' starts a comment.\n" % banner)
        handle.write(header + "\n")
        for row in rows:
            handle.write(render(row) + "\n")


def write_positions(path, provider, rows):
    # '/' rather than ',' so the field never needs quoting.
    _write(path, "%s position eligibility" % provider.capitalize(),
           "name,positions", rows,
           lambda r: "%s,%s" % (r[0], "/".join(r[1])))


def write_ages(path, rows):
    _write(path, "Player ages", "name,age", rows,
           lambda r: "%s,%d" % (r[0], r[1]))


def main():
    tables = {}
    for provider, filename in WORKBOOKS:
        path = os.path.join(cfg_mod.SOURCE_DIR, filename)
        if not os.path.exists(path):
            print("MISSING  %s -- skipping %s" % (filename, provider))
            continue
        rows = read_positions(filename)
        out_path = os.path.join(cfg_mod.CONFIG_DIR,
                                "eligibility_%s.csv" % provider)
        write_positions(out_path, provider, rows)
        tables[provider] = dict(rows)
        print("  %-8s %4d players  ->  config/eligibility_%s.csv"
              % (provider, len(rows), provider))

        # Ages come from one workbook only -- the two carry the same numbers.
        if provider == "yahoo":
            ages = read_ages(filename)
            age_path = os.path.join(cfg_mod.CONFIG_DIR, "ages.csv")
            write_ages(age_path, ages)
            print("  %-8s %4d players  ->  config/ages.csv" % ("ages", len(ages)))

    if len(tables) == 2:
        a, b = tables["yahoo"], tables["fantrax"]
        shared = set(a) & set(b)
        differ = [n for n in shared if a[n] != b[n]]
        print("\n  %d players shared, %d ruled differently by the two platforms"
              % (len(shared), len(differ)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
